---
title: Minga – Food and Climate
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  home:
    title: Startseite
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: home
  values:
    layout: home
    hero_title: 
    hero_subtitle: 
    hero_items: []
    comparison_title: 
    problems_title: 
    problems:
    - content: 
      small_content: 
      icon: 
      include: 
      image: 
      alt: 
      divided: false
      title: 
    solutions_title: 
    solutions:
    - content: 
      small_content: 
      icon: 
      include: 
      image: 
      alt: 
      divided: false
      title: 
    features_title: 
    benefit_title: 
    benefit:
    - content: 
      small_content: 
      icon: 
      include: 
      image: 
      alt: 
      divided: false
      title: 
    donate_title: 
    donate:
    - content: 
      small_content: 
      icon: 
      include: 
      image: 
      alt: 
      divided: false
      title: 
    center_title: 
    center:
    - content: 
      small_content: 
      icon: 
      include: 
      image: 
      alt: 
      divided: false
      title: 
    gallery_title: 
    values_title: 
    values:
    - title: 
      items:
      - content: 
        small_content: 
        icon: 
        include: 
        image: 
        alt: 
        divided: false
        title: 
      button:
        title: 
        url: 
    contact_title: 
    contact_content: 
email: info@minga-app.org
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
url: https://minga-app.org
theme: amp_base_theme
amp_components:
- name: amp-position-observer
- name: amp-animation
google_fonts:
- Montserrat:wght@500
exclude:
- Minga-logo